### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by minad** [text-utf8/META#3]
Hi!

What is the status of this project? Is there some chance that utf8 will ever get upstream or will it just lead to too much breakage of packages relying on the text internals? I was working on a parser library recently and the fact that text uses utf16 internally lead to some complications.

Daniel

**Comment by hvr** [comment]
This project is still very relevant, but the people involved are a bit busy. There's at least two paths to adoption here: either the standard `text` package switches to UTF8 (by being replaced by the `text-utf8` package -- which btw is on Hackage) -- this could also be a cabal flag conditional inside `text` -- or we can wait for Backpack to become mainstream enough, and then you'd simple use `text-utf8` to provide the Text backpack signature.

In any case, if you have time and want to help out with this project, let us know!

**Comment by minad** [comment]
@hvr Thank you for your answer! I agree that the project is very relevant! The memory usage of text-utf8 should be much better and I would also like to have O(1) conversion from bytestring <-> text for valid utf8 bytestrings.

I understand that you are yourself very busy working on many haskell things. However could you list what the open issues are? The backpack solution is certainly elegant but I haven't used it yet. However I think it would be even better to have the best solution in the standard package. Are the upstream maintainers willing to merge this package or do they want more proof that the text-utf8 package is faster? Or is the text package in maintainance mode such that only minor fixes are accepted?

**Comment by hvr** [comment]
@minad Note that I'm not the only one working on this project; The original plan is in fact to merge `text-utf8` back into `text` under some conditions;  Bryan is open to switch to switch the internal rep from UTF16 to UTF8 *if* the numbers are favourable enough and we come up with a good story for supporting `text-icu`; one of the bigger things left to explore is e.g. ripping out the fusion framework from `text-utf8` and review performance impact

**Comment by minad** [comment]
Interesting things you are mentioning. 

I just looked up that icu uses utf16 internally itself. Are the provided utf8 APIs not sufficient? If that is the case I would just drop icu to be honest and replace it with something else despite icu being the standard. Otherwise we are stuck with bad defaults forever. But that's of course a bit radical ;)

The fusion framework issue is much more interesting. Is the plan to implement text-utf8 without fusion support such that the operations become simpler? I've seen that newer prelude approaches like foundation/basement avoid the fusion techniques completely. Can we get some numbers from them?
From my understanding the advantages/disadvantages are as follows:

advantages:
+ better asymptotics in some cases
+ better code reuse, since functions can be expressed as primitives. how often is that the case? would it suffice to just add some more primitive functions in the case without fusion framework.
+ potentially less code due to better reuse

disadvantages:
- hidden magic and complexity
- harder for the compiler to optimize in contrast to working with fast unboxed loops (in particular if fusion does not trigger)
- more code due to the fusion layer

Is that about right? Vector faces the same questions since it is also using a fusion framework.

**Comment by hvr** [comment]
> Are the provided utf8 APIs not sufficient? 

needs to be investigated; worst-case: ICU support pays a performance penalty by going through utf16 and back

Note also the report from the original GSOC (https://jaspervdj.be/posts/2011-08-19-text-utf8-the-aftermath.html) which lamented the ICU issue.

> Is the plan to implement text-utf8 without fusion support such that the operations become simpler?

Ideally; but we need to prove that the performance penalty (if any) is tolerable -> benchmarking -- but we need to benchmark our implementation as otherwise we'd be comparing apples and oranges

also there's a couple tricks I'd like to try on the fusion-less representation to speed up operations for some domains (while hopefully not penalizing others)

The pro/cons you list for fusion seem about right; for me the reduction in complexity is the main motivation; but note that e.g. fusion was suggested for `bytestring`  in the "Rewriting Haskell Strings" paper (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.117.9065&rep=rep1&type=pdf) but in the end `bytestring` did *not* adopt the fusion framework because it didn't pay off.

Finally I'd also like to point to a related discussion on reddit 1-2 years ago: https://www.reddit.com/r/haskell/comments/79oyu1/short_bytestring_and_text/dp497nv/
